### ISSUE TITLE
[Bug]: Error watching  execution of `testSuite`

### ISSUE THREAD

**Issue by andreyLetenkovWefox** [kubeshop/testkube-run-action#7]
### What happened?

Error happens while accessing `stepResults` property within the action

### Version

1.0.0 (Default)

### Relevant log output

```shell
Run kubeshop/testkube-run-action@v1
  with:
    url: https://self-hosted-testkube/api/v1
    testSuite: ts-e2e
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
⸻ Obtaining details
⸻ Scheduling test execution
Execution scheduled: ts-e2e-1 (64d261cbef62b2f5f3f1c5c1)
⸻ Attaching to logs
/opt/actions-runner/_work/_actions/kubeshop/testkube-run-action/v1/dist/index.js:17582
            for (let index = 0; index < stepResults.length; index++) {
                                                    ^

TypeError: Cannot read properties of undefined (reading 'length')
    at TestSuiteEntity.watchExecution (/opt/actions-runner/_work/_actions/kubeshop/testkube-run-action/v1/dist/index.js:17582:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /opt/actions-runner/_work/_actions/kubeshop/testkube-run-action/v1/dist/index.js:17700:1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rangoo94** [comment]
Thank you @andreyLetenkovWefox for the report!

We have recently introduced [**parallel execution**](https://docs.testkube.io/articles/creating-test-suites/) of steps in the test suites, and that has required changing the syntax. This change has not been reflected yet in the `testkube-run-action`, causing the problem you have encountered.

We will get it fixed tomorrow. Sorry for the inconvenience!

**Comment by andreyLetenkovWefox** [comment]
Thank you @rangoo94 for the really fast reply!

**Comment by rangoo94** [comment]
@andreyLetenkovWefox, we've just released the fix, the action should work fine now 🙂 

* If you're using `kubeshop/testkube-run-action@v1` it should work for you immediately, you may restart the failed workflow
* If you're using a direct version (like `@v1.0.4`), you will need to update it to `@v1.0.5`

I hope that Testkube suits you well! 🚀

**Comment by andreyLetenkovWefox** [comment]
Just tested it and it works fine. Thank you once again.
