### ISSUE TITLE
[Bug]: Error while executing testSuites with empty step list

### ISSUE THREAD

**Issue by andreyLetenkovWefox** [kubeshop/testkube-run-action#9]
### What happened?

Action fails while executing Testkube test suite with empty steps list defined. For example:
```
spec:
  description: "Suite of tests to be run as post deployment step"
  steps: []
```

### Version

1.0.0 (Default)

### Relevant log output

```shell
Run kubeshop/testkube-run-action@v1
⸻ Obtaining details
⸻ Scheduling test execution
Execution scheduled: ts-app-postdeploy-1 (64d50740031ed88881789509)
⸻ Attaching to logs
/opt/actions-runner/_work/_actions/kubeshop/testkube-run-action/v1/dist/index.js:17620
            const executions = executeStepResults.map(x => x.execute).flat();
                                                  ^

TypeError: Cannot read properties of undefined (reading 'map')
    at TestSuiteEntity.watchExecution (/opt/actions-runner/_work/_actions/kubeshop/testkube-run-action/v1/dist/index.js:17620:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /opt/actions-runner/_work/_actions/kubeshop/testkube-run-action/v1/dist/index.js:17740:1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rangoo94** [comment]
Hi @andreyLetenkovWefox! Thank you for the report!

We've just released the fix, so the problem should be already solved 🙂

* If you're using `kubeshop/testkube-run-action@v1` it should work for you immediately
* If you're using a direct version (like `@v1.0.4`), you will need to update it to `@v1.0.6`

**Comment by andreyLetenkovWefox** [comment]
Hi @rangoo94! It's working perfectly fine, thank you!
